name: Publish Pig to TestPyPI

on:
  release:
    types: [prereleased, edited]

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Python version
      uses: actions/setup-python@v2 
      with:
        python-version: '3.8'
    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pep517 twine
    - name: Train AI  
      run: |
        python -m pig train ./pig/game/pig_ai -m 1000 -t 0.001
    - name: Build wheel and source tarball
      run: |
        python -m pep517.build . 		
    - name: Publish package
      env:
        TWINE_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
      run: |
        twine upload -r testpypi dist/*


